### ISSUE TITLE
Conditional sections

### ISSUE THREAD

**Issue by kevinferrare** [mrpmorris/Morris.Moxy#47]
It would be nice if we had the ability to switch on / off parts of the mixin template.
Without this, I have to generate preprocessor directives which don't make the generated code look good.
This could be done with the syntax used by mustache (http://mustache.github.io/mustache.5.html#Sections)

**Comment by mrpmorris** [comment]
@moxy
@attribute bool IncludeOptionalStuff
@moxy

{{ if IncludeOptionalStuff }}
  This only appears if you set IncludeOptionalStuff to True in the attribute
{{ end }}
